#!/bin/bash

_ESCAPE=1

echoError() {
    cat <<< "$@" 1>&2; 
}

usage() {
    if [ "$#" -gt 0 ]; then
        echoError ""
        echoError "$@"
    fi
    echoError ""
    echoError "Usage: $0 [-u] value ..."
    echoError ""
    echoError "       -u    - unescape"
    echoError ""
    echoError "       value - Value to escape, or unescape"
    echoError ""
    exit 1
}

while getopts ":u" o; do
    case "${o}" in
        u)
            _ESCAPE=0
            ;;
        *)
            usage "Unknown option specified"
            ;;
    esac
done
shift $((OPTIND-1))

if [ $# -eq 0 ]; then
    usage
fi

if [ $_ESCAPE -eq 1 ]; then
   echo Escaping...
else
   echo Unescaping...
fi
echo

for var in "$@"
do
    if [ $_ESCAPE -eq 1 ]; then
       echo -n $var | perl -MURI::Escape -le 'while(<>) {print "\"$_\" = \"" . uri_escape($_) . "\"";}'
    else
       echo -n $var | perl -MURI::Escape -le 'while(<>) {print "\"$_\" = \"" . uri_unescape($_) . "\"";}'
    fi
done

echo
echo Done.
echo
