#!/bin/bash

echoError() {
    cat <<< "$@" 1>&2; 
}

usage() {
    if [ "$#" -gt 0 ]; then
        echoError ""
        echoError "$@"
    fi
    echoError ""
    echoError "Usage: $0 [-c] [-f] [-g] [-n] [-s] file"
    echoError ""
    echoError "       -c    - Launch Chrome"
    echoError "       -f    - Launch Firefox"
    echoError "       -g    - Do not bring application to the foreground"
    echoError "       -n    - Start a new instance of the application"
    echoError "       -s    - Launch Safari (default)"
    echoError ""
    echoError "       File to open"
    echoError ""
    exit 1
}

_APPNAME="Safari"
_OPENARGS=""

while getopts ":cfgns" o; do
    case "${o}" in
        c)
            _APPNAME="Google Chrome"
            ;;
        f)
            _APPNAME="Firefox"
            ;;
        g)
            _OPENARGS="$_OPENARGS -${o}"
            ;;
        n)
            _OPENARGS="$_OPENARGS -${o}"
            ;;
        s)
            _APPNAME="Safari"
            ;;
        *)
            usage "Unknown option specified"
            ;;
    esac
done
shift $((OPTIND-1))

if [ $# -eq 0 ]; then
    usage
fi

if [ ! -f "$1" ]; then
    echo "Error: '$1' does not exist!"
    exit 1
fi

_APP=/Applications/$_APPNAME.app

if [ ! -e "$_APP" ]; then
    echo "Error: Application '$_APPNAME' does not exist ($_APP)!"
    exit 1
fi

file=`perl -e 'use Cwd "abs_path";print abs_path(shift)' "$1"`
echo "Using '$_APPNAME' to open '$file'..."
open $_OPENARGS -a "/Applications/$_APPNAME.app" "$file"
